# Generated by Django 4.2.6 on 2023-11-27 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuskeepbackend', '0005_claim_answer1_claim_answer2_claim_answer3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_found',
            field=models.BooleanField(default=False),
        ),
    ]
