# Generated by Django 4.2.6 on 2023-11-27 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuskeepbackend', '0007_claim_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(default='', null=True),
        ),
    ]
