# Generated by Django 4.2.6 on 2023-11-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuskeepbackend', '0008_alter_claim_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
