# Generated by Django 4.2.6 on 2023-11-27 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuskeepbackend', '0009_alter_claim_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='description',
            new_name='item_description',
        ),
    ]
