# Generated by Django 4.2.6 on 2023-11-27 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campuskeepbackend', '0010_rename_description_claim_item_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='claim',
            old_name='item_description',
            new_name='description',
        ),
    ]
