# Generated by Django 4.2.6 on 2023-11-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campuskeepbackend', '0012_alter_claim_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='claim',
            name='description',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
